services:
  hoodtv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMDB_API_KEY: ${TMDB_API_KEY}
    ports:
      - "3000:80"
    environment:
      - PORT=8080
    restart: unless-stopped
